//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangJian.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DJContext : DbContext
    {
        public DJContext()
            : base("name=DJContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<V_GradeQuota> V_GradeQuota { get; set; }
        public DbSet<Quota> Quotas { get; set; }
        public DbSet<QuotaGroup> QuotaGroups { get; set; }
        public DbSet<QuotaRecord> QuotaRecords { get; set; }
    }
}
